### PR TITLE
Add support for hale»studio 5.0.1 and Java 17

### PR DESCRIPTION
**Pull request by florianesser**
ING-3997
WGS-2442

### CODE REVIEW

**Comment by florianesser** [comment]
@stempler I can't request a review in this repository. I assume the group "Developers" would need Write access.

**Comment by florianesser** [comment]
Retest this please

**Comment by florianesser** [comment]
Retest this please

**Review by stempler — APPROVED** [review]

**Comment by stempler** [comment]
@florianesser Looks good to me. I'll merge it, do some testing and will probably migrate the build to GitHub actions.

**Pull request merged**
